services:
  - type: web
    name: mirror-origin-g
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: 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